// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions, Firebase;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
 Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW-BUx3nGQehWRcJHKByOe0Q392OBMRzY',
    appId: '1:518057945895:web:00a951d5582e43b55e9702',
    messagingSenderId: '518057945895',
    projectId: 'fsm-application-488017',
    authDomain: 'fsm-application-488017.firebaseapp.com',
    storageBucket: 'fsm-application-488017.firebasestorage.app',
    measurementId: 'G-GKN2HEMRVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8tZtIolEbgzwyp1HU6Bobv4tu_aFqetY',
    appId: '1:518057945895:android:a7bb90af2703fda05e9702',
    messagingSenderId: '518057945895',
    projectId: 'fsm-application-488017',
    storageBucket: 'fsm-application-488017.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPPmsd-IwN-5o7WdOok3Jl--DAUTpbp4c',
    appId: '1:518057945895:ios:5fdd9dc6d56595c35e9702',
    messagingSenderId: '518057945895',
    projectId: 'fsm-application-488017',
    storageBucket: 'fsm-application-488017.firebasestorage.app',
    iosBundleId: 'com.example.fsmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPPmsd-IwN-5o7WdOok3Jl--DAUTpbp4c',
    appId: '1:518057945895:ios:5fdd9dc6d56595c35e9702',
    messagingSenderId: '518057945895',
    projectId: 'fsm-application-488017',
    storageBucket: 'fsm-application-488017.firebasestorage.app',
    iosBundleId: 'com.example.fsmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW-BUx3nGQehWRcJHKByOe0Q392OBMRzY',
    appId: '1:518057945895:web:b5716d5e0b19061a5e9702',
    messagingSenderId: '518057945895',
    projectId: 'fsm-application-488017',
    authDomain: 'fsm-application-488017.firebaseapp.com',
    storageBucket: 'fsm-application-488017.firebasestorage.app',
    measurementId: 'G-SF448T1NCK',
  );

}